### ISSUE TITLE
AgableMob should be AgeableMob

### ISSUE THREAD

**Issue by sekelsta** [SizableShrimp/Forge-Class-Remapper#6]
AgeableEntity gets converted to AgableMob instead of AgeableMob.

**Comment by SizableShrimp** [comment]
This is the exact same as #4. See my related comment [here](https://github.com/SizableShrimp/Forge-Class-Remapper/issues/4#issuecomment-894558520). Basically, in 1.16.5 the class is called `AgableMob`. In 1.17, Mojang fixed the name and renamed it `AgeableMob`. All this script does is remap classnames for the version you are CURRENTLY on, it doesn't actually remap to 1.17 classnames. Mainly because it can't.
